feat: use cargo for tool installation

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -2,13 +2,6 @@
 
 set -exo pipefail
 
-TARGET=$(echo "{{ .chezmoi.os }}" | tr '[:upper:]' '[:lower:]')
-if [[ "$TARGET" == "darwin" ]]; then
-  TARGET="apple-darwin"
-elif [[ "$TARGET" == "linux" ]]; then
-  TARGET="unknown-linux-gnu"
-fi
-
 # --- Helper Functions ---
 log_info() {
   echo "[INFO] $*"
@@ -25,171 +18,26 @@ check_command() {
   }
 }
 
-download_and_extract() {
-  local url="$1"
-  local archive_path="$2"
-  local extract_dir="$3"
-  local strip_components="$4"
-
-  if [[ -d "$extract_dir" ]]; then
-    log_info "Skipping download and extraction: $extract_dir already exists"
-    return 0
-  fi
-
-  # --- Skip download if archive already exists ---
-  if [[ -f "$archive_path" ]]; then
-    log_info "Skipping download: $archive_path already exists"
-  else
-    log_info "Downloading $url"
-    if ! curl -L "$url" -o "$archive_path"; then
-      log_error "Failed to download $url"
-      exit 1
-    fi
-  fi
-
-  # --- Create the target directory ---
-  if [[ ! -d "$extract_dir" ]]; then
-    log_info "Creating directory: $extract_dir"
-    mkdir -p "$extract_dir" || {
-      log_error "Failed to create directory: $extract_dir"
-      exit 1
-    }
-  else
-    log_info "Directory already exists: $extract_dir"
-  fi
-
-  log_info "Extracting $archive_path"
-  if [[ "$archive_path" == *.tar.gz ]]; then
-    if ! tar -xf "$archive_path" -C "$extract_dir" ${strip_components:+"--strip-components=$strip_components"}; then
-      log_error "Failed to extract $archive_path"
-      exit 1
-    fi
-  elif [[ "$archive_path" == *.zip ]]; then
-    check_command unzip
-    if ! unzip "$archive_path" -d "$extract_dir"; then
-      log_error "Failed to extract $archive_path"
-      exit 1
-    fi
-  else
-    log_error "Unsupported archive format: $archive_path"
-    exit 1
-  fi
-}
-
 # --- Check Dependencies ---
 check_command jq
 check_command curl
 
 # --- Install Packages ---
 
+{{- if (eq .chezmoi.os "darwin") }}
 # --- Install Homebrew on macOS ---
-if [[ "$TARGET" == "apple-darwin" ]]; then
-  log_info "Installing Homebrew"
-  if ! command -v brew > /dev/null; then
-    if ! /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; then
-      log_error "Failed to install Homebrew"
-      exit 1
-    fi
-  else
-    log_info "Homebrew already installed. Skipping."
+log_info "Installing Homebrew"
+if ! command -v brew > /dev/null; then
+  if ! /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; then
+    log_error "Failed to install Homebrew"
+    exit 1
   fi
-fi
-
-# difftastic
-if [[ "$TARGET" == "apple-darwin" ]]; then
-  # --- Install packages with Homebrew on macOS ---
-  log_info "Installing packages with Homebrew"
-  brew install difftastic fd ripgrep bat zellij neovim direnv zoxide starship uv ast-grep
 else
-	DIFFTASTIC_VERSION=$(curl -Ls https://api.github.com/repos/Wilfred/difftastic/releases/latest | jq -r ".tag_name")
-
-	download_and_extract \
-	"https://github.com/Wilfred/difftastic/releases/download/$DIFFTASTIC_VERSION/difft-aarch64-$TARGET.tar.gz" \
-	"/tmp/difftastic-$DIFFTASTIC_VERSION.tar.gz" \
-	"/tmp/difftastic-$DIFFTASTIC_VERSION" \
-	0
-
-	mv "/tmp/difftastic-$DIFFTASTIC_VERSION/difft" ~/.local/bin
-	chmod u+x ~/.local/bin/difft
-	rm -rf "/tmp/difftastic-$DIFFTASTIC_VERSION"*
-
-	# fd
-	FD_VERSION=$(curl -Ls https://api.github.com/repos/sharkdp/fd/releases/latest | jq -r ".tag_name")
-	download_and_extract \
-	"https://github.com/sharkdp/fd/releases/download/$FD_VERSION/fd-$FD_VERSION-aarch64-$TARGET.tar.gz" \
-	"/tmp/fd-$FD_VERSION.tar.gz" \
-	"/tmp/fd-$FD_VERSION" \
-	1
-
-	mv "/tmp/fd-$FD_VERSION/fd" ~/.local/bin
-	chmod u+x ~/.local/bin/fd
-	rm -rf "/tmp/fd-$FD_VERSION"*
-
-	# ripgrep
-	RIPGREP_VERSION=$(curl -Ls https://api.github.com/repos/BurntSushi/ripgrep/releases/latest | jq -r ".tag_name")
-	download_and_extract \
-	"https://github.com/BurntSushi/ripgrep/releases/download/$RIPGREP_VERSION/ripgrep-$RIPGREP_VERSION-aarch64-$TARGET.tar.gz" \
-	"/tmp/ripgrep-$RIPGREP_VERSION.tar.gz" \
-	"/tmp/ripgrep-$RIPGREP_VERSION" \
-	1
-
-	mv "/tmp/ripgrep-$RIPGREP_VERSION/rg" ~/.local/bin
-	chmod u+x ~/.local/bin/rg
-	rm -rf "/tmp/ripgrep-$RIPGREP_VERSION"*
-
-	# eza
-
-	EZA_VERSION=$(curl -Ls https://api.github.com/repos/eza-community/eza/releases/latest | jq -r ".tag_name")
-
-	# Determine the correct eza binary name based on TARGET
-	EZA_BINARY="eza_x86_64-unknown-linux-musl.tar.gz"
-
-	# Download and extract (this part remains the same)
-	download_and_extract \
-	"https://github.com/eza-community/eza/releases/download/$EZA_VERSION/$EZA_BINARY" \
-	"/tmp/eza-$EZA_VERSION.tar.gz" \
-	"/tmp/eza-$EZA_VERSION"
-
-	mv "/tmp/eza-$EZA_VERSION/eza" ~/.local/bin
-	chmod u+x ~/.local/bin/eza
-	rm -rf "/tmp/eza-$EZA_VERSION"*
-
-	# bat
-	BAT_VERSION=$(curl -Ls https://api.github.com/repos/sharkdp/bat/releases/latest | jq -r ".tag_name")
-
-	# Determine the correct bat binary name based on TARGET
-	if [[ "$TARGET" == "apple-darwin" ]]; then
-	BAT_BINARY="bat-$BAT_VERSION-x86_64-apple-darwin.tar.gz"
-	elif [[ "$TARGET" == "unknown-linux-gnu" ]]; then
-	BAT_BINARY="bat-$BAT_VERSION-aarch64-unknown-linux-gnu.tar.gz"
-	else
-	log_error "Unsupported target for bat: $TARGET"
-	exit 1
-	fi
-
-	download_and_extract \
-	"https://github.com/sharkdp/bat/releases/download/$BAT_VERSION/$BAT_BINARY" \
-	"/tmp/bat-$BAT_VERSION.tar.gz" \
-	"/tmp/bat-$BAT_VERSION" \
-	1
-
-	mv "/tmp/bat-$BAT_VERSION/bat" ~/.local/bin
-	chmod u+x ~/.local/bin/bat
-	rm -rf "/tmp/bat-$BAT_VERSION"*
-
-	# zellij
-	ZELLIJ_VERSION=$(curl -Ls https://api.github.com/repos/zellij-org/zellij/releases/latest | jq -r ".tag_name")
-	download_and_extract \
-	"https://github.com/zellij-org/zellij/releases/download/$ZELLIJ_VERSION/zellij-aarch64-unknown-linux-musl.tar.gz"
-	"/tmp/zellij-$ZELLIJ_VERSION.tar.gz" \
-	"/tmp/zellij-$ZELLIJ_VERSION"
-
-	mv "/tmp/zellij-$ZELLIJ_VERSION/zellij" ~/.local/bin
-	chmod u+x ~/.local/bin/zellij
-	rm -rf "/tmp/zellij-$ZELLIJ_VERSION"*
+  log_info "Homebrew already installed. Skipping."
 fi
+{{- end }}
 
-# rustup and neovim
+# --- rustup ---
 log_info "Installing rustup"
 if ! command -v rustup > /dev/null; then
   if ! curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh; then
@@ -200,10 +48,33 @@ else
   rustup update
 fi
 
-rustup default stable
+# --- Source cargo env ---
+log_info "Sourcing cargo environment"
+source "$HOME/.cargo/env"
 
+# --- Cargo Installations ---
+# Function to install a cargo package and handle errors
+install_cargo_package() {
+  local package_name="$1"
+  log_info "Installing $package_name"
+  if ! cargo install "$package_name" --locked; then
+    log_error "Failed to install $package_name"
+    exit 1
+  fi
+}
+
+# Install cargo packages using the function
+install_cargo_package ast-grep
+install_cargo_package difftastic
+install_cargo_package fd-find
+install_cargo_package ripgrep
+install_cargo_package eza
+install_cargo_package bat
+install_cargo_package zellij
+
+# --- Neovim ---
 log_info "Installing Neovim"
-pushd "$HOME/.local/"
+pushd "$HOME/.local/" || exit 1
 if ! curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage \
   && chmod u+x nvim.appimage \
   && ./nvim.appimage --appimage-extract \
@@ -211,9 +82,9 @@ if ! curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.app
   log_error "Failed to install Neovim"
   exit 1
 fi
-popd
+popd || exit 1
 
-# direnv, zoxide, starship, and uv
+# --- Other Installations ---
 PREFIX=~/.local/bin
 mkdir -p "$PREFIX"
 
@@ -246,9 +117,4 @@ else
   uv self update
 fi
 
-# ast-grep
-log_info "Installing ast-grep"
-if ! cargo install ast-grep --locked; then
-  log_error "Failed to install ast-grep"
-  exit 1
-fi
+log_success "All tools installed successfully!"
