Correct wrong order of dirs

diff --git a/run_once_install-packages.sh.tmpl b/run_once_install-packages.sh.tmpl
--- a/run_once_install-packages.sh.tmpl
+++ b/run_once_install-packages.sh.tmpl
@@ -31,17 +31,6 @@ download_and_extract() {
   local extract_dir="$3"
   local strip_components="$4"
 
-  # --- Create the target directory ---
-  if [[ ! -d "$extract_dir" ]]; then 
-    log_info "Creating directory: $extract_dir" 
-    mkdir -p "$extract_dir" || { 
-      log_error "Failed to create directory: $extract_dir"
-      exit 1
-    }
-  else
-    log_info "Directory already exists: $extract_dir"
-  fi
-
   if [[ -d "$extract_dir" ]]; then
     log_info "Skipping download and extraction: $extract_dir already exists"
     return 0
@@ -52,7 +41,16 @@ download_and_extract() {
     log_error "Failed to download $url"
     exit 1
   fi
-
+  # --- Create the target directory ---
+  if [[ ! -d "$extract_dir" ]]; then 
+    log_info "Creating directory: $extract_dir" 
+    mkdir -p "$extract_dir" || { 
+      log_error "Failed to create directory: $extract_dir"
+      exit 1
+    }
+  else
+    log_info "Directory already exists: $extract_dir"
+  fi
   log_info "Extracting $archive_path"
   if [[ "$archive_path" == *.tar.gz ]]; then
     if ! tar -xf "$archive_path" -C "$extract_dir" ${strip_components:+"--strip-components=$strip_components"}; then
